name: Bug报告 | Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **感谢您的反馈！| Thanks for taking the time to fill out this bug report!**
            有关功能建议，疑问或非bug类, 请查看[讨论区](https://github.com/clipturbo/clipturbo/discussions)
              For feature, questions, or other request, please consider using [Github Discussion](https://github.com/clipturbo/clipturbo/discussions) instead.
            请先查找是否已有类似的 [问题](https://github.com/clipturbo/clipturbo/issues)
              Please search [issue](https://github.com/clipturbo/clipturbo/issues) before asking
  - type: input
    id: version
    attributes:
      label: 小视频宝版本号 | Version
      description: What version of our app are you running?
      placeholder: 0.1.0
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 平台 | Platform
      description: What platform are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
  - type: textarea
    id: describe
    attributes:
      label: 请描述这个Bug | Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 出现问题的模板 | Template
      description: 哪一个模板上出现的问题？
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: 重现步骤 | To Reproduce
      description: Steps to reproduce the behavior
      placeholder: 1. Go to '...' 2. Click translate
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 补充说明 | Additional context
      description: Add any other context about the problem here.
