blank_issues_enabled: false
contact_links:
  - name: 新功能建议 | Feature request
    url: https://github.com/clipturbo/clipturbo/discussions/new?category=ideas
    about: Feature requests should be opened as discussions
  - name: 其它问题 | Ask a question
    url: https://github.com/clipturbo/clipturbo/discussions/new?category=help
    about: Ask questions and discuss with other community members
